### ISSUE TITLE
Develop in Mac

### ISSUE THREAD

**Issue by demonixis** [NOLOVR/NOLO-Unity-SDK#1]
Hi,

Having only a unityPackage prevent the community to contribute to the SDK. By example, the current version can't be compiled on a Mac (there are errors because of some `#if UNITY_STANDALONE_WIN`) or other platforms of Android and WIndows. I have fixed that but I can't submit a pull request because the sources are not visibles.

Thanks.

**Comment by LyrobotixNolo** [comment]
Our server is only run in the windows,we can't debug in mac,so you can Set up a branch,then i link to your branch

**Comment by demonixis** [comment]
Hi,
I'll prepare a repo with the uncompressed sources on a `master` branch, then a modification of the source for Windows Store, Mac and other platforms. Don't worry It's not complicated and it not alter the sources.

I added a NoloVR_NullPlatform which does nothing on unsuported platforms and few other fixes.

**Comment by demonixis** [comment]
Hi,

I don't know why you've changed the title of this issue, it's not related to developing on Mac, but on all platforms. This PR #4 fixes the problem, please merge it.

**Comment by LyuzhouZ** [comment]
We've modified our code based on your suggestion. One can now develop games that support Nolo with Unity on all platforms. However, currently Nolo is only supported on Windows, hence the debugging process.
