### ISSUE TITLE
The position tracking is inconsistant and the SDK unstable

### ISSUE THREAD

**Issue by demonixis** [NOLOVR/NOLO-Unity-SDK#5]
Hi,

I'm trying to add NoloVR support into my game GunSpinning VR (PC, Mobile), the implementation is done, but it's totaly unplayable because of few points

1. The head tracking shakes a lot
2. The position of the hands are incorrect
3. The SDK is unstable (resulting Unity Editor to crash)

Please take a look at this video to [see the problem](https://www.facebook.com/groups/NOLOVR/permalink/1779514242360407/)

## My setup
- Windows 10 Creator Update
- Nolo Runtime 0.5.0
- All leds are green
- Unity 5.6 and 2017.1
- OSVR HDK2 and nothing (I also test without the headset, just with the headblob)

## Inconsistant tracking
As you can see on the video, the tracking is unstable, it shakes and it's hard to calibrate. I've made tests in differents positions, tried to remove all lights (dark room), no sounds, etc... But that's not the problem. With all my tests, it's very hard to get a consistant tracking more than 1 minute.

## Bad hand position
The positions of the hands are bad, there are too far of the camera. I suggest to add a `recenter` function, exactly like Oculus, Vive, Ximmerse to recenter the position of the headset and the hand (aka put all position/rotations to 0, 0, 0).

## Unstable SDK
The SDK is unstable, if you start a scene and stop the editor, a new start will freezes the editor.
If I call the `Disconnect()` method from Nolo_Playform in the `OnDestroy` method, it crashes the editor.
I think you've a memory leak somewhere.

## About my game
[GunSpinning VR](https://demonixis.itch.io/gunspinning-vr) is a wild west VR Shooter with zombies. It'll be released very soon on Android and GearVR with Ximmerse support and I really want to enable the NoloVR support too ;) However, I can't enable it with all these issues.

Thank you,
demonixis.

**Comment by Hettylool** [comment]
@demonixis 
hi, 
thank you a lot.and i will Improve these problems.
did you change the place to play? we just wand to figure out is the environmental impact or equipment problems.

**Comment by Hettylool** [comment]
@demonixis  
we have update a new version Version 1.1.3.did it still crashes?

**Comment by demonixis** [comment]
Hi,

As I said on Facebook and on the NOLO-Other repository, I tried my NoloVR kit in all rooms (living room, kitchen), with and without lights. I moved the base station in many configurations and the result is the same. I think I've a bad unit.

I don't see a new version, I already use the 1.1.3 and the problem is still here. What Unity version do you use? Can you play a demo more than 2 time? Also can you call the disconnect method without a crash?

**Comment by Hettylool** [comment]
@demonixis 

the first version is 1.1.2 ,i commit on May 25, 2017,at that time you change is support mac. that version have the problem like what you said.

the second version is 1.1.3,i Commits on Jun 18, 2017, I have made an improvement on these problems.i will check it again,

and about your NoloVR Kit, I will ask my colleague for solution.

thank you!

**Comment by demonixis** [comment]
OK thank you! As I said, I already updated to 1.1.3, I check this repository all days, so when you push a change, I push it to my repo (see #4 ) and I update my game.

Ultimately have you a mail? Because I can send you a beta of my game on PC or mobile. You'll be able to try yourselft an tell me if it's my NoloVR kit or the Unity plugin.

**Comment by Hettylool** [comment]
@demonixis 
Of cause ,my email is :     zhenze@lyrobotix.com   

Thank you for your support.

**Comment by demonixis** [comment]
Hi,

It's very strange but from today, I'm able to use the NoloVR! I tested my game with the controllers and it's almot fine. Sometime I loose the tracking and I don't know why. Please take a look at [this video](https://www.youtube.com/watch?v=PCRH9godDL4&feature=youtu.be). The tracking is weird at the end of the video. The position of the controllers are bad (behind me). Everything else looks good.
You may notice a small shake of the controllers, I can add some smooth but it seems to already be the case.
I'll send you a version today.
