### ISSUE TITLE
GearVR NOLO Problems

### ISSUE THREAD

**Issue by patstarace** [NOLOVR/NOLO-Unity-SDK#6]
Hi,

I'm having problems with NOLO and Gear VR. I built the "Test" scene and deployed to the S7 as per the SDK  and Getting Started docs. I start the game and insert the phone into the GearVR, plug in the cable, the light on headset turns from red to green. Scene starts but I don't have any trackers. I double clicked on the controllers and nothing happens.

I tried building for Cardboard and was successful, though the rotation data from the phone is sub par. I would really prefer to use the sensors of the GearVR.

Any suggestions would be welcome.

Thank you,

~Pat

**Comment by Hettylool** [comment]
@patstarace  
hi,
start the game and insert the phone into the GearVR,when you plug the headset marker in the GearVR,do you see a System prompt window in GearVR "Whether to allow applications to access USB devices" ,and select "sure/yes".

**Comment by patstarace** [comment]
@Hettylool 
I've done that many times. Start the app, insert the phone into the GearVR and I get the USB connected window, but NOLO doesn't start working. I've tried using Unity 5.6, 5.5, 5.4.1, and always the same thing. I've gotten this to work with Cardboard but the sensors are nowhere as good as gear. Any thoughts on what could be the problem. Thanks ~Pat

**Comment by Hettylool** [comment]
@patstarace 
Hi,  the headset marker should bu plug in Gear VR not windows,and what's your GearVR version?is that a white one or a black one?

**Comment by patstarace** [comment]
@Hettylool 
My headtracker is plugged into the GearVR with the OTG cable, and it's LED turns from red to green. I have a Samsung S7 and Black GearVR 2017. I get the "Allow USB" popup on the GearVR when first starting up a newly built app, and I click "Yes".  The HeadTracker USB seems to be recognized as a USB device but no data seems to be transferred. 
Thank you for your help,
~Pat

**Comment by patstarace** [comment]
Any more help on why NOLO is not working with GearVR and Unity Android would be greatly appreciated.

Build Environment:
GearVR 2016 Blue / 2017 Black
Samsung S7 Android 6.0.1 Marshmallow
Unity 5.4.1 / 5.5 / 5.6
Android JDK 1.8.0_101
OTG Cables - NOLO OTG and 3rd party OTG cable

I've tried everything I can think of to build for GearVR, but NOLO doesn't want to work. I start the app, insert the phone into the GearVR, plug the headtracker into the GVR, Headtracker light turns green, put GearVR on , USB popup appears on the device, but NOLO doesn't start. I've done everything as per the instructions, and am looking for a solution.

Can someone please help?

Thank you,
~Pat

**Comment by Hettylool** [comment]
@patstarace 
hi,
it seem all step is right.
 USB popup appears on the device choose yes,but you can't see controller and you can't move?

make sure base station is on ,and two controller's light is green.

try the app without GearVR, you can build a no gearvr app and make sure the nolo device is ok？

**Comment by patstarace** [comment]
@Hettylool 

YES! USB popup appears and I choose Yes. Then I'm in the scene and I can see the play area, controllers but when I double click the controllers nothing happens.

base station in on, and all controllers lights are green.

As I wrote earlier, I have successfully built for Cardboard and when I double click the controllers system buttons twice the tracking resets and NOLO works GREAT!

What could the problem be? SDK? Settings? Versions?

Thank you,
~Pat

**Comment by Hettylool** [comment]
@patstarace 
hi 
double click should be write by yourself.
you can find a scripts in asssts/NoloVR/Example/Recenter/NoloVR_Recenter.cs
this is a scripts about double click recenter method.
if you build a gearvr
you can :
using UnityEngine.VR;
InputTracking.Recenter();
to recenter.

**Comment by patstarace** [comment]
@Hettylool 

I'm looking into what you suggested, but I don't seem to have any tracking working. When I move my head the playfield and controllers move with me, and when I move my controllers nothing moves. Shouldn't tracking be working before I recenter, unless re-centering starts the tracking process.

When I built for Cardboard and started the app, I had tracking working when I moved my head and controllers, then I performed a recenter, but when I build for Gear tracking isn't working at all.

Is there anything I need to do in the scripts to turn NOLO tracking on for Gear?

I hope we get this worked out soon.

Thank you for your help,
~Pat

**Comment by patstarace** [comment]
@Hettylool 

Also in NoloVR_Manager there is this line.

[Tooltip("if you develop a gear app choose Gear,else choose Cardboard")]

But there doesn't seem to be a way to choose. Has this been removed from an earlier version of the SDK?

Thank you,
~Pat

**Comment by patstarace** [comment]
@Hettylool 
hi
Would you be able to provide a working Test Scene for GearVR?

Regards,
~Pat

**Comment by Hettylool** [comment]
@patstarace 
hi
can you send me your oculus sign file,and i will build a test sence to you.
my email is : zhenze@lyrobotix.com


and [Tooltip("if you develop a gear app choose Gear,else choose Cardboard")]
it is just let me now what camera do you used. it is different.No matter which one you choose，the tracking will not be affected.

**Comment by patstarace** [comment]
@Hettylool 
sent

**Comment by patstarace** [comment]
@Hettylool 
hi

After many attempts Nolo still doesn't track. I think Unity/GearVR is unable to communicate with Nolo.  I've debugged and Nolo only get as far //try to connect the usb device.

Any help would be greatly appreciated.

Thank you,
~Pat

**Comment by Hettylool** [comment]
@patstarace 
Hi,
 jo.Call("usb_conn");
this method should be called  after
 when you plug the nolo in Gear and 
select sure when gearvr system prompt “Allow applications to access USB devices”！
i was call this method in NoloVR_Manager.cs with a loop until it is success!

**Comment by patstarace** [comment]
@Hettylool 
Hi,
I created a GearVR button event in NoloVR_Manager that would call ("usb_conn") in the ConnectDevice() function. This still results in a zero return from "usb_conn". I tried a loop, but it didn't work either (maybe I didn't do it correctly). Would you have an example of how to accomplish this?

The allow USB prompt in GearVR is different than in Carboard. The GearVR prompt upon initial launch looks like this:
"NoloGVR3(app name) is requesting permission to access photos, media, and files on your device. Allow? Deny Allow" I select "Allow".
Does this look correct to you?

Since Nolo does work when I build for Cardboard, might I have a faulty Nolo OTG Cable/Adapter for use with GearVR?

Thank you for all your help,
~Pat

**Comment by Hettylool** [comment]
@patstarace 

Hi,
Maybe you should change the usb line,the short line(one side is micro usb ,another side is micro usb&type-c)may not work very well.
please change it and try it again.

**Comment by patstarace** [comment]
@Hettylool 
I'm using the short OTG cable, and I have to use the USB-C adapter to fit into the GearVR. I tried the adapter on the other end and still the same problem exists.

**Comment by Hettylool** [comment]
@patstarace  
so ,this short OTG may can't work,change another one.

**Comment by patstarace** [comment]
I tried a 3rd party OTG cable and still the problem exists.

**Comment by Hettylool** [comment]
the usb line,which connect nolo headset to GearVR.
you must see  “Allow applications to access USB devices”  and select allow.it will work.
not "NoloGVR3(app name) is requesting permission to access photos, media, and files on your device. Allow? Deny Allow" ,this also should select "Allow"

**Comment by Hettylool** [comment]
@patstarace 
adapter maybe  is bad too,

**Comment by Hettylool** [comment]
it is important that you build is good for my test.so is not the project wrong.
