### ISSUE TITLE
Unable to find libNoloVrUnity

### ISSUE THREAD

**Issue by fjallraven** [NOLOVR/NOLO-Unity-SDK#9]
Testing building the example scenes provided in package 1.1.4_20170718
Unity is set to android, oculus etc - as in the developer guide.

Getting this on two phones, galaxy s5 and phab 2 pro

Both were connected via usb and "build & run" in Unity

libNoloVrUnity.so is in the packaged apk for both arm/x86.
Just to confirm:
```
shell@klte:/data/app/com.abcdef.nolovrtest2-2/lib/arm $ ls
libNoloVrUnity.so
libOVRPlugin.so
libmain.so
libmono.so
libunity.so
libvrapi.so
```

Launching the apk:
`07-29 22:06:42.041: E/Unity(8622): Unable to find libNoloVrUnity`

Running the tetris app from google play works fine on both phones.

Any ideas?

**Comment by Hettylool** [comment]
try the new version again,libNoloVrUnity should be in plugin/android/lib/..Unity should include this file when it build.

**Comment by fjallraven** [comment]
Getting the same issue with latest package.
Changed NoloVR_Plugins.cs:181 to
`public const string dllName = "NoloVrUnity";`
and error went away.

However I'm seeing the following:
```
08-08 21:07:52.677: E/UsbCustomTransfer(4048): 外设支持HID 协议
08-08 21:07:52.677: E/UsbCustomTransfer(4048): USB 输出端点
08-08 21:07:52.687: E/UsbCustomTransfer(4048): USB 输入端点长度64
```
What does this mean? Phone is connected to head tracker everything is switched on and green.
